In [12]:
import os
os.getcwd()

'D:\\JUPYTER NOTEBOOK--1\\DSMP-2\\FEATURE_ENGINEERING\\NOTEBOOKS'

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df = pd.read_csv(r'D:\JUPYTER NOTEBOOK--1\DSMP-2\FEATURE_ENGINEERING\datasets\customer (1).csv')

In [14]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [15]:
df.shape

(50, 5)

In [16]:
df=df.drop(columns=['age','gender'])
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [17]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [18]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [21]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [22]:
X_train=oe.fit_transform(X_train)
X_test=oe.transform(X_test)

In [28]:
oe.categories

[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]

In [33]:
oe.feature_names_in_

array(['review', 'education'], dtype=object)

In [38]:
oe.inverse_transform(np.array([0,2]).reshape(1,2))

array([['Poor', 'PG']], dtype=object)

In [43]:
oe.get_feature_names_out()

array(['review', 'education'], dtype=object)

## SETTING FOR THR UNKNOWN INPUTS

In [44]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']],
                 handle_unknown='use_encoded_value',
                 unknown_value=-1 
                 )

X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)
X_train=oe.fit_transform(X_train)
X_test=oe.transform(X_test)

In [45]:
oe.transform(np.array(['Poor','College']).reshape(1,2))

C:\Users\moham\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[ 0., -1.]])

array([[1., 1., 2., 1., 2.],
       [0., 1., 1., 2., 2.],
       [1., 0., 0., 2., 1.],
       [0., 0., 2., 2., 0.],
       [0., 0., 0., 1., 2.],
       [1., 2., 0., 0., 2.],
       [0., 2., 0., 2., 2.],
       [2., 2., 2., 0., 2.],
       [1., 0., 1., 1., 2.],
       [1., 1., 1., 0., 2.],
       [1., 1., 0., 2., 2.],
       [0., 0., 2., 1., 1.],
       [1., 2., 2., 1., 2.],
       [1., 1., 0., 1., 2.],
       [0., 0., 1., 2., 0.],
       [1., 2., 0., 2., 2.]])